### ISSUE TITLE
Abandon Penitence Textbox Overflows

### ISSUE THREAD

**Issue by NeonPixels** [BrandenEK/Blasphemous.Framework.Penitence#2]
When abandoning a custom penitence that has a very long description, the textbox overflows.
If possible, adding the scroll bar functionality would solve this.
![AbandonPenitenceTextboxOverflow](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/1130b276-a250-42f0-a6a3-1750d9102958)

**Comment by NeonPixels** [comment]
Investigating the code, the only difference I see between the `ChoosePenitenceWidget` and `AbandonPenitenceWidget` regarding the textbox is that the former has the following attribute:
```
[SerializeField]
private CustomScrollView penitenceScroll;
```

This is initialized when adding the description text to the textbox:
```
public void Option_SelectPE01()
{
	this.penitenceTitle.text = ScriptLocalization.UI_Penitences.PE01_NAME;
	this.penitenceInfoText.text = ScriptLocalization.UI_Penitences.PE01_INFO;
	this.penitenceScroll.NewContentSetted();
}
```

So if there is a way to add the attribute and initialize it when setting the `AbandonPenitenceWidget` description, it might work.

**Comment by NeonPixels** [comment]
Hmmm, looking more into it... First of all, we can't use patching to add properties to classes, so we can't add a CustomScrollView to the AbandonPenitenceWidget class, as far as I know.

Then the CustomScrollView needs to have its area defined on the Unity editor.

Not sure how to do a workaround for this.

**Comment by BrandenEK** [comment]
If we can fix that I would certainly like to have it in here.  However, the CustomScrollView is almost certainly a component that was placed using the editor, so it will be very difficult to create a new one and add it to this UI element

**Comment by NeonPixels** [comment]
I will tinker with it eventually and see if I find a solution, but right now I think it is more of a "nice to have" feature, specially since it seems like it requires a lot of work for little gain.

Maybe a simpler fix in this case would be to trim the description text so it always fits on the textbox. The description will still be incomplete, but it won't look as ugly.

I'm going to do a couple tests to see how many characters fit in the box for the different languages and will report back.

**Comment by NeonPixels** [comment]
Made the following tests. The '.' character indicates 50 character blocks, and the ';' indicates 100 character blocks. Of course, the '.' and ';' need to be counted too.
These are the results with the different character sets:

- Base font (Spanish, English, German, French, Portuguese):
![AbandonPenitenceTextbox_BaseFont](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/36848749-719c-47f8-a1f2-dd753ad340a7)

- Chinese font:
![AbandonPenitenceTextbox_ZhFont](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/6680ad00-2678-498a-a445-18fe735fd96d)

- Russian font:
![AbandonPenitenceTextbox_RuFont](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/2068dd9b-e47f-4e93-a0dc-a38c8b36d4c5)

- Japanese font:
![AbandonPenitenceTextbox_JpFont](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/c113e594-facc-4769-8e0e-7f1b9ccb93f8)

- Korean font:
![AbandonPenitenceTextbox_KoFont](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/99ef354a-5a6a-45c8-9ec4-d31045ada074)

**Comment by NeonPixels** [comment]
So I have tried cropping the text in the code and... It isn't as simple a fix as it seems. This is how it looks when cropping to 400 characters using the basic font:

![AbandonPenitenceTextbox_BaseFont_400](https://github.com/BrandenEK/Blasphemous.Framework.Penitence/assets/82003471/dcb8e973-b3fc-4941-b77b-f79d870a4a3e)

The problems with this approach are the following:

- The fonts are not necessarily monospace, so a hard cap on the number of characters will not guarantee that the text is cut properly
- Asian fonts are much larger, so trimming the text to make them fit will excessively trim all other fonts, unless the code detects the language and applies a font-specific character limit.
- Newlines count as single characters, but add an entire line to the text (each line is approximately 35 characters long in the base font), and, worse yet, there is no easy way to know how many characters are already in the line before the newline. So unless the trimming code does some magic to manage newlines, the hard cap won't always work.

So the "simple" solution is not that simple after all.

**Comment by BrandenEK** [comment]
Can you try setting the height of the text field and possibly changing the overflow mode so that it cuts off the text automatically

**Comment by NeonPixels** [comment]
Will look into it!
